/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sc202.proyectofinal_sistemadeventadeverduleria;

import CRUD.ManejoProductos;
import javax.swing.JOptionPane;

/**
 *
 * @author jrg71
 */
public class frm_Admin_BorrarProductos extends javax.swing.JFrame {

    /**
     * Creates new form frm_Admin_BorrarProductos
     */
    public frm_Admin_BorrarProductos() {
        initComponents();
        this.getRootPane().setDefaultButton(btnEliminar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBorrarProductos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIDBorrar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lblBorrarProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBorrarProductos.setForeground(new java.awt.Color(255, 255, 255));
        lblBorrarProductos.setText("Borrar Producto");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID de Producto");

        txtIDBorrar.setBackground(new java.awt.Color(57, 62, 70));
        txtIDBorrar.setForeground(new java.awt.Color(255, 255, 255));

        btnEliminar.setBackground(new java.awt.Color(57, 62, 70));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(57, 62, 70));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtIDBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(lblBorrarProductos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBorrarProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String idBuscar = txtIDBorrar.getText();
        ManejoProductos objManejoProductos = new ManejoProductos();
        
        if (idBuscar.contains("FRU-")){
            objManejoProductos.setTipoProducto("Frutas");
            objManejoProductos.setIdProductoManejoArchivos(idBuscar);
            int encontroRegistro = objManejoProductos.borrarPorID();
            
            if (encontroRegistro==1){
                JOptionPane.showMessageDialog(null,"El registro fue eliminado correctamente");
            }else{
                JOptionPane.showMessageDialog(null, "No fue encontrado el ID en el sistema, vuelva a intentarlo");
            }
            
            limpiaCajasDeArchivos();
        }else if (idBuscar.contains("VER-")){
            objManejoProductos.setTipoProducto("Verduras");
            objManejoProductos.setIdProductoManejoArchivos(idBuscar);
            int encontroRegistro = objManejoProductos.borrarPorID();
            
            if (encontroRegistro==1){
                JOptionPane.showMessageDialog(null,"El registro fue eliminado correctamente");
            }else{
                JOptionPane.showMessageDialog(null, "No fue encontrado el ID en el sistema, vuelva a intentarlo");
            }
            
            limpiaCajasDeArchivos();
        }else if (idBuscar.contains("OTR-")){
            objManejoProductos.setTipoProducto("Otros");
            objManejoProductos.setIdProductoManejoArchivos(idBuscar);
            int encontroRegistro = objManejoProductos.borrarPorID();
            
            if (encontroRegistro==1){
                JOptionPane.showMessageDialog(null,"El registro fue eliminado correctamente");
            }else{
                JOptionPane.showMessageDialog(null, "No fue encontrado el ID en el sistema, vuelva a intentarlo");
            }
            
            limpiaCajasDeArchivos();
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese una ID válido");
            limpiaCajasDeArchivos();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void limpiaCajasDeArchivos(){
        txtIDBorrar.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Admin_BorrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Admin_BorrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Admin_BorrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Admin_BorrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Admin_BorrarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBorrarProductos;
    private javax.swing.JTextField txtIDBorrar;
    // End of variables declaration//GEN-END:variables
}
