/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sc202.proyectofinal_sistemadeventadeverduleria;

import CRUD.ManejoPersonas;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jrg71
 */
public class frm_Clientes_ListarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frm_Clientes_ListarUsuario
     */
    public frm_Clientes_ListarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagenCorreo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblImagenPassword = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtCorreoConsulta = new javax.swing.JTextField();
        lblNombreResult = new javax.swing.JLabel();
        lblCedulaResult = new javax.swing.JLabel();
        lblNumeroResult = new javax.swing.JLabel();
        lblDireccionResult = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtPasswordConsulta = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lblImagenCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/user.png"))); // NOI18N
        lblImagenCorreo.setToolTipText("");

        lblUsuario.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(26, 77, 46));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Datos de usuario");

        lblCedula.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(26, 77, 46));
        lblCedula.setText("Cédula:");

        lblNombre.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(26, 77, 46));
        lblNombre.setText("Nombre:");

        lblImagenPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/password.png"))); // NOI18N

        lblNumero.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(26, 77, 46));
        lblNumero.setText("Número:");

        lblDireccion.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(26, 77, 46));
        lblDireccion.setText("Dirección:");

        txtCorreoConsulta.setBackground(new java.awt.Color(26, 77, 46));
        txtCorreoConsulta.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        txtCorreoConsulta.setForeground(new java.awt.Color(0, 0, 0));

        lblNombreResult.setBackground(new java.awt.Color(26, 77, 46));
        lblNombreResult.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        lblNombreResult.setForeground(new java.awt.Color(26, 77, 46));

        lblCedulaResult.setBackground(new java.awt.Color(26, 77, 46));
        lblCedulaResult.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        lblCedulaResult.setForeground(new java.awt.Color(26, 77, 46));

        lblNumeroResult.setBackground(new java.awt.Color(26, 77, 46));
        lblNumeroResult.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        lblNumeroResult.setForeground(new java.awt.Color(26, 77, 46));

        lblDireccionResult.setBackground(new java.awt.Color(26, 77, 46));
        lblDireccionResult.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        lblDireccionResult.setForeground(new java.awt.Color(26, 77, 46));

        btnConsultar.setBackground(new java.awt.Color(26, 77, 46));
        btnConsultar.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(26, 77, 46));
        btnSalir.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtPasswordConsulta.setBackground(new java.awt.Color(26, 77, 46));
        txtPasswordConsulta.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        txtPasswordConsulta.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion)
                            .addComponent(lblNumero)
                            .addComponent(lblCedula)
                            .addComponent(lblNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreResult)
                            .addComponent(lblCedulaResult)
                            .addComponent(lblNumeroResult)
                            .addComponent(lblDireccionResult)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagenCorreo)
                            .addComponent(lblImagenPassword))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnConsultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(btnSalir))
                            .addComponent(txtCorreoConsulta)
                            .addComponent(txtPasswordConsulta)))
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImagenCorreo)
                    .addComponent(txtCorreoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImagenPassword)
                    .addComponent(txtPasswordConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultar)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblNombreResult))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(lblCedulaResult))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(lblNumeroResult))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(lblDireccionResult))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        ManejoPersonas objManejoPersonas = new ManejoPersonas();
        Cliente objCliente = new Cliente();
        ArrayList <Cliente> listaClientes = new ArrayList<Cliente>();
        
        String correoCliente = txtCorreoConsulta.getText();
        String passwordCliente = String.valueOf(txtPasswordConsulta.getPassword());
        
        if ((correoCliente.length()>=1)&&(passwordCliente.length()>=1)){
            objCliente.setCorreoElectronicoPersona(correoCliente);
            objManejoPersonas.setContraseñaSesion(passwordCliente);
            listaClientes= objManejoPersonas.consultaCliente(objCliente);
            
            lblNombreResult.setText(listaClientes.get(0).getNombrePersona());
            lblCedulaResult.setText(listaClientes.get(0).getCedulaPersona());
            lblNumeroResult.setText(listaClientes.get(0).getNumeroTelefonicoPersona());
            lblDireccionResult.setText(listaClientes.get(0).getDireccionCliente());
        }else {
            JOptionPane.showMessageDialog(null,"Ingrese sus credenciales");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Clientes_ListarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Clientes_ListarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Clientes_ListarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Clientes_ListarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Clientes_ListarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedulaResult;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccionResult;
    private javax.swing.JLabel lblImagenCorreo;
    private javax.swing.JLabel lblImagenPassword;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreResult;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroResult;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtCorreoConsulta;
    private javax.swing.JPasswordField txtPasswordConsulta;
    // End of variables declaration//GEN-END:variables
}
