/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sc202.proyectofinal_sistemadeventadeverduleria;

import CRUD.ManejoPersonas;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import sc202.proyectofinal_sistemadeventadeverduleria.Cliente;

/**
 *
 * @author jrg71
 */
public class frm_Clientes_RegistrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frm_Clientes_RegistrarUsuario
     */
    public frm_Clientes_RegistrarUsuario() {
        initComponents();
        this.getRootPane().setDefaultButton(btnRegistrar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegistrarCliente = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblMetodoPago = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtMetodoPago = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblRegistrarCliente.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblRegistrarCliente.setForeground(new java.awt.Color(26, 77, 46));
        lblRegistrarCliente.setText("Registrar Usuario");

        lblNombre.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");

        lblEdad.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(255, 255, 255));
        lblEdad.setText("Edad");

        lblCedula.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(255, 255, 255));
        lblCedula.setText("Cédula");

        lblNumero.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setText("Número Telefónico");

        lblDireccion.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Dirección");

        lblMetodoPago.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lblMetodoPago.setForeground(new java.awt.Color(255, 255, 255));
        lblMetodoPago.setText("Método de Pago");

        btnRegistrar.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(57, 62, 70));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(57, 62, 70));
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(57, 62, 70));

        txtEdad.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(57, 62, 70));

        txtCedula.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(57, 62, 70));

        txtNumero.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(57, 62, 70));

        txtDireccion.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(57, 62, 70));

        txtMetodoPago.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        txtMetodoPago.setForeground(new java.awt.Color(57, 62, 70));

        lblCorreo.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo");

        lblPassword.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Contraseña");

        txtCorreo.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(57, 62, 70));

        txtPassword.setForeground(new java.awt.Color(57, 62, 70));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(btnRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNombre)
                                            .addComponent(lblEdad)
                                            .addComponent(lblCedula)
                                            .addComponent(lblCorreo))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNombre)
                                            .addComponent(txtEdad)
                                            .addComponent(txtCedula)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDireccion)
                                            .addComponent(lblMetodoPago)
                                            .addComponent(lblPassword)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(lblNumero)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(txtMetodoPago)
                            .addComponent(txtDireccion)
                            .addComponent(txtNumero)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lblRegistrarCliente)))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblRegistrarCliente)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblNumero)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMetodoPago)
                    .addComponent(txtMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(lblPassword)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnSalir))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        String edad = txtEdad.getText();
        String cedula = txtCedula.getText();
        String telefono = txtNumero.getText();
        String direccionClientes = txtDireccion.getText();
        String metodoPagoClientes = txtMetodoPago.getText();
        String usuario = txtCorreo.getText();
        String contraseña = String.valueOf(txtPassword.getPassword());
        
        Cliente objCliente = new Cliente();
        ManejoPersonas objManejoPersonas = new ManejoPersonas();

        if ((nombre.length() >= 1) && (edad.length() >= 1) && (cedula.length() >= 1) && (telefono.length() >= 1) && (direccionClientes.length() >= 1) && (metodoPagoClientes.length() >= 1) && (usuario.contains("@")) && (contraseña.length() >= 5)) {
            if (isNumeric(edad)) {
                objManejoPersonas.setContraseñaSesion(contraseña);
                objCliente.setIdCliente("CLI-AR");
                objCliente.setCorreoElectronicoPersona(usuario);
                objCliente.setNombrePersona(nombre);
                objCliente.setEdadPersona(Integer.parseInt(edad));
                objCliente.setCedulaPersona(cedula);
                objCliente.setNumeroTelefonicoPersona(telefono);

                objCliente.setDireccionCliente(direccionClientes);
                objCliente.setMetodoPagoCliente(metodoPagoClientes);

                objManejoPersonas.agregarCliente(objCliente);
                limpiaCajasDeArchivos();
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese los datos del tipo requerido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos requeridos, recuerde que la contraseña debe ser de almos 5 dígitos");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private static boolean isNumeric(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }
    private void limpiaCajasDeArchivos() {
        txtNombre.setText("");
        txtEdad.setText("");
        txtCedula.setText("");
        txtNumero.setText("");
        txtDireccion.setText("");
        txtMetodoPago.setText("");
        txtCorreo.setText("");
        txtPassword.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Clientes_RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Clientes_RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Clientes_RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Clientes_RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Clientes_RegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblMetodoPago;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegistrarCliente;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtMetodoPago;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
